### PR TITLE
Laravel 8 and Bref 1.* support

### PR DESCRIPTION
**Pull request by korridor**
This fixes the problems for me, but I am not sure if this works in all cases.
This changes do not work with Laravel 5.8.* and I only tested it with Laravel 8.27.0.

### CODE REVIEW

**Comment by christoph-kluge** [comment]
@korridor thank you so much for filing this PR and investigating into this case.

I didn't updated my installations to L8 yet but I would attempt to verify you changes against my L7 installatiosn and see if I can add find a balance between quick support and backward-compatibility. In case it's not possible I would perhaps consider a new release.

Will keep you posted on this.

**Comment by christoph-kluge** [comment]
@korridor I took your changes and validated it with my adoptions against my L7 + bref 0.5.x installations. They are still supported.

May I ask you to check if this branch is also working against your L8 + bref 1.2.x version? If that's the case I will create a new release today.

https://github.com/christoph-kluge/bref-sqs-laravel/tree/pr/9

**Comment by korridor** [comment]
@christoph-kluge No worries and thanks for the fast response. I tested the changes with two emails that I dispatched through this queue. The application uses Laravel 8 and bref 1.2.0.

**Comment by korridor** [comment]
@christoph-kluge No worries and thanks for the fast response. I tested the changes in the `pr/9` branch with two emails that I dispatched through this queue. The application uses Laravel 8.28.0 and bref 1.2.0.

**Comment by christoph-kluge** [comment]
@korridor thank you for filing this PR. I took your changes and made slight adjustments here: #10 and merged the code.

**Pull request closed without merging**
